spring:
   flyway:
     baseline-on-migrate: true
   datasource:
     url: jdbc:postgresql://localhost:5432/school_db
     username: postgres
     password: qwerty123

logging:
  level:
    root: WARN
    org.foxminded.rymarovych: DEBUG
