INSERT INTO courses (name)
VALUES ('Biology'),
       ('Math'),
       ('Art'),
       ('History'),
       ('Physics'),
       ('Chemistry'),
       ('English'),
       ('P.E.'),
       ('Algebra'),
       ('Geometry');

INSERT INTO groups (name)
VALUES ('WP-10'),
       ('DS-35'),
       ('MF-23'),
       ('VC-33'),
       ('LW-34');

INSERT INTO students_courses (student_id, course_id)
VALUES (1, 8),
       (1, 9),
       (2, 4),
       (2, 5),
       (2, 4),
       (3, 2),
       (3, 5),
       (3, 3),
       (4, 8),
       (4, 6),
       (4, 3),
       (5, 6),
       (5, 6),
       (6, 3),
       (6, 5),
       (6, 6),
       (7, 5),
       (8, 5),
       (9, 8),
       (9, 1),
       (10, 8),
       (11, 9),
       (11, 8),
       (11, 8),
       (12, 3),
       (12, 5),
       (13, 1),
       (13, 4),
       (14, 2),
       (14, 9),
       (15, 2),
       (16, 5),
       (16, 7),
       (17, 7),
       (18, 8),
       (19, 5),
       (20, 3),
       (21, 8);

INSERT INTO students (group_id, first_name, last_name)
VALUES (1, 'Miles', 'Thomas'),
       (1, 'Brian', 'Lewis'),
       (1, 'Jorge', 'Roberts'),
       (2, 'Brian', 'Green'),
       (2, 'Miles', 'Williams'),
       (2, 'Debra', 'Harris'),
       (2, 'John', 'Thomas'),
       (2, 'Jorge', 'Harris'),
       (2, 'Isabel', 'Edwards'),
       (2, 'Stella', 'Edwards'),
       (4, 'Stella', 'Thomas'),
       (4, 'Dan', 'Lewis'),
       (4, 'Dan', 'Williams'),
       (4, 'Jorge', 'Robinson'),
       (4, 'John', 'Lewis'),
       (5, 'Vera', 'Robinson'),
       (5, 'Lucy', 'Brown'),
       (5, 'John', 'Smith'),
       (5, 'Isabel', 'Green'),
       (5, 'Jorge', 'Wilson');